name: fcatt
description: face attendance.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Functionality
  camera: ^0.10.5+5
  # ---- THIS IS THE CORRECTED LINE ----
  google_mlkit_face_detection: ^0.9.0
  # ------------------------------------
  geolocator: ^10.1.0
  http: ^1.1.0
  image: ^4.1.3 # For image processing like cropping

  # Utilities
  path_provider: ^2.1.1
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0 # For loading animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
